# Блок 2

## Задача 3
Очистка строк:  
**Условие:** Дана таблица `data (id, name)`.  
В поле `name` перемешаны визуально одинаковые
кириллические и латинские символы (а/а, о/о, с / с и т.д.).  
**Задание:** Приведи имена к единому виду(к одной системе письма),
затем найди дубликаты и присвой каждой группе дублей новый new_id.

In [11]:
import pandas as pd

df = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['Иван', 'Иваn', 'Ивaн', 'Мария', 'Mapия', 'Пaвeл']
})
df

   id   name
0   1   Иван
1   2   Иваn
2   3   Ивaн
3   4  Мария
4   5  Mapия
5   6  Пaвeл

In [16]:
latin_to_cyr = str.maketrans({
    'a': 'а', 'e': 'е', 'o': 'о', 'p': 'р', 'c': 'с',
    'x': 'х', 'y': 'у', 'n': 'н', 'k': 'к', 'm': 'м',
    'A': 'А', 'E': 'Е', 'O': 'О', 'P': 'Р', 'C': 'С',
    'X': 'Х', 'T': 'Т', 'H': 'Н', 'B': 'В', 'M': 'М', 'K': 'К'
})

df['name_cleaned'] = (df['name']
                    .str.translate(latin_to_cyr)
                    .str.strip())

# присваиваем new_id
df['new_id'] = df.groupby('name_cleaned')['id'].transform('min')
df[['new_id','name_cleaned']]

   new_id name_cleaned
0       1         Иван
1       1         Иван
2       1         Иван
3       4        Мария
4       4        Мария
5       6        Павел